/*
 * MINT_config.h
 *
 *  Created on: Apr 10, 2020
 *      Author: Mahmoud
 */

#ifndef CSWC_PLT_MCU_ATMEGA32_MINT_MINT_CONFIG_H_
#define CSWC_PLT_MCU_ATMEGA32_MINT_MINT_CONFIG_H_

//{MINT_INT#,MINT_ON-MINT_OFF,MINT_RISINGEDGE-MINT_FALLINGEDGE-MINT_LOGICALEDGE}
MINT_Config MINT_Init_INT0={MINT_INT0,
					   MINT_ON,
					   MINT_LOGICALEDGE
};
MINT_Config MINT_Init_INT1={MINT_INT1,
					   MINT_ON,
					   MINT_RISINGEDGE
};
MINT_Config MINT_Init_INT2={MINT_INT2,
					   MINT_ON,
					   MINT_RISINGEDGE
};


#endif /* CSWC_PLT_MCU_ATMEGA32_MINT_MINT_CONFIG_H_ */
