/*
 * MDIO_Config.h
 *
 *  Created on: Apr 6, 2020
 *      Author: Mahmoud
 */

#ifndef CSWC_PLT_MCU_ATMEGA32_MDIO_MDIO_CONFIG_H_
#define CSWC_PLT_MCU_ATMEGA32_MDIO_MDIO_CONFIG_H_

// MDIO_OUTPUT MDIO_INPUT
#define MDIO_DIR_PINNO_0   MDIO_OUTPUT
#define MDIO_DIR_PINNO_1   MDIO_OUTPUT
#define MDIO_DIR_PINNO_2   MDIO_OUTPUT
#define MDIO_DIR_PINNO_3   MDIO_OUTPUT
#define MDIO_DIR_PINNO_4   MDIO_OUTPUT
#define MDIO_DIR_PINNO_5   MDIO_OUTPUT
#define MDIO_DIR_PINNO_6   MDIO_OUTPUT
#define MDIO_DIR_PINNO_7   MDIO_OUTPUT
#define MDIO_DIR_PINNO_8   MDIO_OUTPUT
#define MDIO_DIR_PINNO_9   MDIO_OUTPUT
#define MDIO_DIR_PINNO_10  MDIO_OUTPUT
#define MDIO_DIR_PINNO_11  MDIO_OUTPUT
#define MDIO_DIR_PINNO_12  MDIO_OUTPUT
#define MDIO_DIR_PINNO_13  MDIO_OUTPUT
#define MDIO_DIR_PINNO_14  MDIO_OUTPUT
#define MDIO_DIR_PINNO_15  MDIO_OUTPUT
#define MDIO_DIR_PINNO_16  MDIO_OUTPUT
#define MDIO_DIR_PINNO_17  MDIO_OUTPUT
#define MDIO_DIR_PINNO_18  MDIO_OUTPUT
#define MDIO_DIR_PINNO_19  MDIO_OUTPUT
#define MDIO_DIR_PINNO_20  MDIO_OUTPUT
#define MDIO_DIR_PINNO_21  MDIO_OUTPUT
#define MDIO_DIR_PINNO_22  MDIO_OUTPUT
#define MDIO_DIR_PINNO_23  MDIO_OUTPUT
#define MDIO_DIR_PINNO_24  MDIO_OUTPUT
#define MDIO_DIR_PINNO_25  MDIO_OUTPUT
#define MDIO_DIR_PINNO_26  MDIO_OUTPUT
#define MDIO_DIR_PINNO_27  MDIO_OUTPUT
#define MDIO_DIR_PINNO_28  MDIO_OUTPUT
#define MDIO_DIR_PINNO_29  MDIO_OUTPUT
#define MDIO_DIR_PINNO_30  MDIO_OUTPUT
#define MDIO_DIR_PINNO_31  MDIO_OUTPUT
//MDIO_OUTPUTHIGH MDIO_OUTPUTLOW
#define MDIO_PORT_NO_0      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_1      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_2      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_3      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_4      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_5      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_6      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_7      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_8      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_9      MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_10     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_11     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_12     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_13     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_14     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_15     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_16     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_17     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_18     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_19     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_20     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_21     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_22     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_23     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_24     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_25     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_26     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_27     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_28     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_29     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_30     MDIO_HIGHOUTPUT
#define MDIO_PORT_NO_31     MDIO_HIGHOUTPUT

//MDIO_PULLUP MDIO_HIGHIMPEDANCE
#define MDIO_PINNO_0          MDIO_PULLUP
#define MDIO_PINNO_1          MDIO_PULLUP
#define MDIO_PINNO_2          MDIO_PULLUP
#define MDIO_PINNO_3          MDIO_PULLUP
#define MDIO_PINNO_4          MDIO_PULLUP
#define MDIO_PINNO_5          MDIO_PULLUP
#define MDIO_PINNO_6          MDIO_PULLUP
#define MDIO_PINNO_7          MDIO_PULLUP
#define MDIO_PINNO_8          MDIO_PULLUP
#define MDIO_PINNO_9          MDIO_PULLUP
#define MDIO_PINNO_10         MDIO_PULLUP
#define MDIO_PINNO_11         MDIO_PULLUP
#define MDIO_PINNO_12         MDIO_PULLUP
#define MDIO_PINNO_13         MDIO_PULLUP
#define MDIO_PINNO_14         MDIO_PULLUP
#define MDIO_PINNO_15         MDIO_PULLUP
#define MDIO_PINNO_16         MDIO_PULLUP
#define MDIO_PINNO_17         MDIO_PULLUP
#define MDIO_PINNO_18         MDIO_PULLUP
#define MDIO_PINNO_19         MDIO_PULLUP
#define MDIO_PINNO_20         MDIO_PULLUP
#define MDIO_PINNO_21         MDIO_PULLUP
#define MDIO_PINNO_22         MDIO_PULLUP
#define MDIO_PINNO_23         MDIO_PULLUP
#define MDIO_PINNO_24         MDIO_PULLUP
#define MDIO_PINNO_25         MDIO_PULLUP
#define MDIO_PINNO_26         MDIO_PULLUP
#define MDIO_PINNO_27         MDIO_PULLUP
#define MDIO_PINNO_28         MDIO_PULLUP
#define MDIO_PINNO_29         MDIO_PULLUP
#define MDIO_PINNO_30         MDIO_PULLUP
#define MDIO_PINNO_31         MDIO_PULLUP


#endif /* CSWC_PLT_MCU_ATMEGA32_MDIO_MDIO_CONFIG_H_ */
