/*
 * MTIMERS_Private.h
 *
 *  Created on: Apr 12, 2020
 *      Author: Mahmoud
 */

#ifndef CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_PRIVATE_H_
#define CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_PRIVATE_H_



#endif /* CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_PRIVATE_H_ */
