/*
 * MTIMERS_config.h
 *
 *  Created on: Apr 12, 2020
 *      Author: Mahmoud
 */

#ifndef CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_CONFIG_H_
#define CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_CONFIG_H_


//MPGT_TIM0_ON    MPGT_TIM0_OFF
#define MGPT_TIM0_MODE   MPGT_TIM0_ON

//MPGT_TIM0_NORMAL -MPGT_TIM0_PWM_PC- MPGT_TIM0_FAST_PWM MPGT_TIM0_CTC
#define MGPT_TIMER_0_WG

#endif /* CSWC_PLT_MCU_ATMEGA32_MTIMERS_MTIMERS_CONFIG_H_ */
